apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ template "app.fullname" . }}
      containers:
      - name: operator-init-crds
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
        volumeMounts:
        - name: data-crds
          mountPath: /etc/operator-init
          readOnly: true
        command: ["kubectl",  "apply", "-f", "/etc/operator-init/."]
      volumes:
      - name: data-crds
        configMap:
          name: {{ template "app.fullname" . }}
      restartPolicy: Never
  backoffLimit: 3
