apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{ toYaml .Values.serviceSelectorLabels | indent 4 }}
  name: expose-kube-dns-metrics
  namespace: {{ default .Release.Namespace .Values.componentNamespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: {{ .Values.ports.metrics.dnsmasq.name }}
    port: {{ .Values.ports.metrics.dnsmasq.port }}
    protocol: {{ .Values.ports.metrics.dnsmasq.protocol }}
    targetPort: {{ .Values.ports.metrics.dnsmasq.port }}
  - name: {{ .Values.ports.metrics.skydns.name }}
    port: {{ .Values.ports.metrics.skydns.port }}
    protocol: {{ .Values.ports.metrics.skydns.protocol }}
    targetPort: {{ .Values.ports.metrics.skydns.port }}
{{- if not .Values.endpoints }}
  selector:
{{ toYaml .Values.serviceSelectorLabels | indent 4 }}
{{- end }}