apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-init-crd-11
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-init-service-account
      containers:
      - name: istio-init-crd-11
        image: "{{ template "system_default_registry" . }}{{ .Values.global.kubectl.repository }}:{{ .Values.global.kubectl.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        volumeMounts:
        - name: crd-11
          mountPath: /etc/istio/crd-11
          readOnly: true
        command: ["kubectl",  "apply", "-f", "/etc/istio/crd-11/crd-11.yaml"]
      volumes:
      - name: crd-11
        configMap:
          name: istio-crd-11
      restartPolicy: OnFailure
{{- if .Values.deleteCRDs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-init-delete-crd-11
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-init-service-account
      containers:
      - name: istio-init-crd-11
        image: "{{ template "system_default_registry" . }}{{ .Values.global.kubectl.repository }}:{{ .Values.global.kubectl.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        volumeMounts:
        - name: crd-11
          mountPath: /etc/istio/crd-11
          readOnly: true
        command: ["kubectl",  "delete", "-f", "/etc/istio/crd-11/crd-11.yaml"]
      volumes:
      - name: crd-11
        configMap:
          name: istio-crd-11
      restartPolicy: OnFailure
{{- end }}
