apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{ toYaml .Values.serviceSelectorLabels | indent 4 }}
  name: expose-kube-scheduler-metrics
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: {{ .Values.ports.metrics.name }}
    port: {{ .Values.ports.metrics.port }}
    protocol: {{ .Values.ports.metrics.protocol }}
    targetPort: {{ .Values.ports.metrics.port }}
{{- if not .Values.endpoints }}
  selector:
{{ toYaml .Values.serviceSelectorLabels | indent 4 }}
{{- end }}
