## 
## For now, HELM cannot support deploy commponents into multiple namespaces
##
componentNamespace: ""

## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Custom endpoints
##
endpoints: []

ports: 
  metrics:
    scheme: http
    name: http-metrics
    port: 10251
    protocol: TCP

serviceSelectorLabels:
  component: kube-scheduler

serviceMonitorLabels: {}

prometheusRuleLabels: {}

## Skip verification until we have resolved why the certificate validation
## for the kubelet on API server nodes fail.
##
insecureSkipVerify: true
