apiVersion: {{ template "apiregistration_api_version" . }}
kind: APIService
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    namespace: {{ .Release.Namespace }}
    name: access-prometheus-adapter
  group: custom.metrics.k8s.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
  {{ if .Values.tls.enabled -}}
  caBundle: {{ b64enc .Values.tls.ca }}
  insecureSkipTLSVerify: false
  {{- else }}
  insecureSkipTLSVerify: true
  {{- end }}


{{- if not (.Capabilities.APIVersions.Has "external.metrics.k8s.io/v1beta1") }}
---
apiVersion: {{ template "apiregistration_api_version" . }}
kind: APIService
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    namespace: {{ .Release.Namespace }}
    name: access-prometheus-adapter
  group: external.metrics.k8s.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
  {{ if .Values.tls.enabled -}}
  caBundle: {{ b64enc .Values.tls.ca }}
  insecureSkipTLSVerify: false
  {{- else }}
  insecureSkipTLSVerify: true
  {{- end }}
{{- end }}


{{- if not (.Capabilities.APIVersions.Has "metrics.k8s.io/v1beta1") }}
---
apiVersion: {{ template "apiregistration_api_version" . }}
kind: APIService
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: v1beta1.metrics.k8s.io
spec:
  service:
    namespace: {{ .Release.Namespace }}
    name: access-prometheus-adapter
  group: metrics.k8s.io
  version: v1beta1
  groupPriorityMinimum: 100
  versionPriority: 100
  {{ if .Values.tls.enabled -}}
  caBundle: {{ b64enc .Values.tls.ca }}
  insecureSkipTLSVerify: false
  {{- else }}
  insecureSkipTLSVerify: true
  {{- end }}
{{- end }}
