apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: access-prometheus-adapter
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
  - name: https
    port: 443
    targetPort: https