apiVersion: v1
kind: Pod
metadata:
  name: sonobuoy
  {{- if ne .Values.owner "" }}
  annotations:
    field.cattle.io/clusterScanOwner: "{{ .Values.owner }}"
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "rancher-cis-benchmark.name" . }}
    helm.sh/chart: {{ include "rancher-cis-benchmark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # TODO: make the sa name configurable
  serviceAccountName: sonobuoy-serviceaccount
  volumes:
    - configMap:
        name: sonobuoy-config-cm
      name: sonobuoy-config-volume
    - configMap:
        name: sonobuoy-plugins-cm
      name: sonobuoy-plugins-volume
    - emptyDir: {}
      name: output-volume
  containers:
    - name: {{ .Chart.Name }}
      restartPolicy: Never
      env:
        - name: SONOBUOY_ADVERTISE_IP
          value: {{ include "rancher-cis-benchmark.fullname" . }}
        {{- if ne .Values.owner "" }}
        - name: CONFIGMAPNAME
          value: {{ .Release.Name }}
        {{- end }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/sonobuoy
          name: sonobuoy-config-volume
        - mountPath: /plugins.d
          name: sonobuoy-plugins-volume
        - mountPath: /tmp/sonobuoy
          name: output-volume
      resources:
        {{- toYaml .Values.resources | nindent 12 }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
{{- end }}
