## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

ports: 
  metrics:
    scheme: http
    name: metrics
    
serviceSelectorLabels:
  k8s-app: fluentd

serviceMonitorLabels: {}

## Skip verification until we have resolved why the certificate validation
## for the kubelet on API server nodes fail.
##
insecureSkipVerify: true
