apiVersion: v1
name: rancher-gke-operator
description: A Helm chart for provisioning GKE clusters
home: https://github.com/rancher/gke-operator
sources:
  - "https://github.com/rancher/gke-operator"
version: 2.0.100
appVersion: v2.0.1-rc1
