enabledRBAC: true

## Already exist ServiceAccount
##
serviceAccountName: ""

## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

# Default values for kube-state-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/coreos/kube-state-metrics
  tag: v1.4.0

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 130Mi

## Node Selector to constrain pods to run on particular nodes
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
nodeSelectors: []

## Tolerations for use with node taints
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
  #  - key: "key"
  #    operator: "Equal"
  #    value: "value"
  #    effect: "NoSchedule"

serviceMonitorLabels: {}

securityContext: {}
