## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

ports: 
  metrics:
    scheme: https
    name: https

serviceSelectorLabels:
  component: apiserver
  provider: kubernetes

insecureSkipVerify: true
