## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

ports: 
  metrics:
    scheme: https
    name: https

serviceSelectorLabels:
  component: apiserver
  provider: kubernetes

serviceMonitorLabels: {}

prometheusRuleLabels: {}

insecureSkipVerify: true
